name: smart_wallet
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: any
  sqlite3_flutter_libs: ^0.5.17
  intl: ^0.18.1
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  mask_text_input_formatter: ^2.7.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "E2E6ED"
  image: "assets/logo.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/

