// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIMbxeX0aLyDClDyvgW-UNUpo4CvCmzU',
    appId: '1:938520681942:web:cb9e6d6606d6edf8301877',
    messagingSenderId: '938520681942',
    projectId: 'smartwalletcatolica',
    authDomain: 'smartwalletcatolica.firebaseapp.com',
    databaseURL: 'https://smartwalletcatolica-default-rtdb.firebaseio.com',
    storageBucket: 'smartwalletcatolica.appspot.com',
    measurementId: 'G-YFLY110H6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5g4qx8r4IJGtdtzu66hBSMbKnGC5c0o',
    appId: '1:938520681942:android:1e038d68fb16b8ef301877',
    messagingSenderId: '938520681942',
    projectId: 'smartwalletcatolica',
    databaseURL: 'https://smartwalletcatolica-default-rtdb.firebaseio.com',
    storageBucket: 'smartwalletcatolica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2n8bpM86EIRuuySfcHDkoLILSnHAr6LU',
    appId: '1:938520681942:ios:c9fd3720be763e97301877',
    messagingSenderId: '938520681942',
    projectId: 'smartwalletcatolica',
    databaseURL: 'https://smartwalletcatolica-default-rtdb.firebaseio.com',
    storageBucket: 'smartwalletcatolica.appspot.com',
    iosBundleId: 'com.example.smartWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2n8bpM86EIRuuySfcHDkoLILSnHAr6LU',
    appId: '1:938520681942:ios:bcd6806359e2134e301877',
    messagingSenderId: '938520681942',
    projectId: 'smartwalletcatolica',
    databaseURL: 'https://smartwalletcatolica-default-rtdb.firebaseio.com',
    storageBucket: 'smartwalletcatolica.appspot.com',
    iosBundleId: 'com.example.smartWallet.RunnerTests',
  );
}
